# Generated by Django 3.1.2 on 2020-11-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_recipes', '0002_recipe_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horn_length', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'oxen',
                'ordering': ['horn_length'],
            },
        ),
    ]
