# Generated by Django 3.1.2 on 2020-11-03 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_recipes', '0003_ox'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ox',
        ),
    ]
